/* Meteora — ship anchors. GENERATED by tools/blender/build_ships.py from the
   empties in fighter.glb and interceptor.glb; do not edit by hand.

   glTF / three.js space, metres: nose along -Z, top +Y, right +X; Blender
   (x, y, z) maps to (x, z, -y). `radius` bounds the hull from the origin.
   Nozzle `dir` is the exhaust direction (the empty's Blender local -Y); RCS
   `dir` is the puff direction out of the hull (Blender local +Z), so a port
   pushes the ship along -dir. `cockpit` is the nose-camera eye point. */
export const ANCHORS = {
  fighter: {
    radius: 7.65,
    nozzles: [
      { name: 'nozzle_L', pos: [-1.2, 0, 7.43], dir: [0, 0, 1] },
      { name: 'nozzle_R', pos: [1.2, 0, 7.43], dir: [0, 0, 1] },
    ],
    muzzles: [
      { name: 'muzzle_L', pos: [-5.42, 0.175, -3.335] },
      { name: 'muzzle_R', pos: [5.42, 0.175, -3.335] },
    ],
    rcs: [
      { name: 'rcs_01', pos: [-0.002, 0.544, -5.016], dir: [0, 1, 0] },
      { name: 'rcs_02', pos: [0.001, -0.46, -5.003], dir: [0, -1, 0] },
      { name: 'rcs_03', pos: [0.983, -0.02, -5], dir: [1, 0, 0] },
      { name: 'rcs_04', pos: [-0.981, -0.02, -5], dir: [-1, 0, 0] },
      { name: 'rcs_05', pos: [-0.002, 0.683, 5.757], dir: [0, 1, 0] },
      { name: 'rcs_06', pos: [0.001, -0.514, 5.753], dir: [0, -1, 0] },
      { name: 'rcs_07', pos: [1.922, -0.009, 5.199], dir: [1, 0, 0] },
      { name: 'rcs_08', pos: [-1.922, -0.009, 5.199], dir: [-1, 0, 0] },
      { name: 'rcs_09', pos: [5.42, 0.487, 1.9], dir: [0, 1, 0] },
      { name: 'rcs_10', pos: [5.42, -0.136, 1.9], dir: [0, -1, 0] },
      { name: 'rcs_11', pos: [-5.42, 0.487, 1.9], dir: [0, 1, 0] },
      { name: 'rcs_12', pos: [-5.42, -0.136, 1.9], dir: [0, -1, 0] },
      { name: 'rcs_13', pos: [0.391, 0.211, -5.955], dir: [0.286, 0.0953, -0.9535] },
      { name: 'rcs_14', pos: [-0.391, 0.211, -5.955], dir: [-0.286, 0.0953, -0.9535] },
      { name: 'rcs_15', pos: [0.259, 0.219, 6.896], dir: [0, 0, 1] },
      { name: 'rcs_16', pos: [-0.259, 0.219, 6.896], dir: [0, 0, 1] },
    ],
    cockpit: [0, 0.98, -2.95],
  },
  interceptor: {
    radius: 5.75,
    nozzles: [
      { name: 'nozzle_C', pos: [0, 0.02, 5.46], dir: [0, 0, 1] },
    ],
    muzzles: [
      { name: 'muzzle_L', pos: [-0.98, -0.62, -2.705] },
      { name: 'muzzle_R', pos: [0.98, -0.62, -2.705] },
    ],
    rcs: [
      { name: 'rcs_01', pos: [0, 0.289, -3.961], dir: [0, 1, 0] },
      { name: 'rcs_02', pos: [0, -0.307, -3.954], dir: [0, -1, 0] },
      { name: 'rcs_03', pos: [0.499, 0, -4.25], dir: [1, 0, 0] },
      { name: 'rcs_04', pos: [-0.499, 0, -4.25], dir: [-1, 0, 0] },
      { name: 'rcs_05', pos: [0, 0.895, 3.35], dir: [0, 1, 0] },
      { name: 'rcs_06', pos: [0, -0.855, 3.35], dir: [0, -1, 0] },
      { name: 'rcs_07', pos: [1.609, -0.15, 3.3], dir: [1, 0, 0] },
      { name: 'rcs_08', pos: [-1.609, -0.15, 3.3], dir: [-1, 0, 0] },
      { name: 'rcs_09', pos: [4.332, 1.425, -0.749], dir: [0, 1, 0] },
      { name: 'rcs_10', pos: [3.881, -1.214, 0.101], dir: [0, -1, 0] },
      { name: 'rcs_11', pos: [-4.332, 1.425, -0.749], dir: [0, 1, 0] },
      { name: 'rcs_12', pos: [-3.881, -1.214, 0.101], dir: [0, -1, 0] },
      { name: 'rcs_13', pos: [0.351, 0.017, -4.555], dir: [0.286, 0.0953, -0.9535] },
      { name: 'rcs_14', pos: [-0.351, 0.018, -4.555], dir: [-0.286, 0.0953, -0.9535] },
      { name: 'rcs_15', pos: [0.5, 0.61, 4.36], dir: [0, 0, 1] },
      { name: 'rcs_16', pos: [-0.5, 0.61, 4.36], dir: [0, 0, 1] },
    ],
    cockpit: [0, 0.5, -2.4],
  },
};
